export const ERROR_CODES = {
    // auth_error_codes.py
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    MISSING_ACCESS_TOKEN: 'MISSING_ACCESS_TOKEN',
    INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
    MISSING_REFRESH_TOKEN: 'MISSING_REFRESH_TOKEN',
    INVALID_SESSION: 'INVALID_SESSION',
    EMAIL_NOT_ALLOWED: 'EMAIL_NOT_ALLOWED',
    INVALID_SIGNUP_SECRET: 'INVALID_SIGNUP_SECRET',
    USER_NOT_FOUND: 'USER_NOT_FOUND',

    // common_error_codes.py
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_RESOURCE_ID: 'INVALID_RESOURCE_ID',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    FORBIDDEN: 'FORBIDDEN',
    ALLOWLIST_DISABLED: 'ALLOWLIST_DISABLED',
    BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
    INFRASTRUCTURE_ERROR: 'INFRASTRUCTURE_ERROR',
    HTTP_ERROR: 'HTTP_ERROR',
    UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',

    // external_error_codes.py
    INVALID_GOOGLE_TOKEN: 'INVALID_GOOGLE_TOKEN',
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',

    // odin_error_codes.py
    INCOME_SOURCE_NOT_FOUND: 'INCOME_SOURCE_NOT_FOUND',
    ALLOCATION_BOX_NOT_FOUND: 'ALLOCATION_BOX_NOT_FOUND',
    SUBCATEGORY_NOT_FOUND: 'SUBCATEGORY_NOT_FOUND',
    ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
    PERCENTAGE_EXCEEDS_LIMIT: 'PERCENTAGE_EXCEEDS_LIMIT'
} as const;
