export const ERROR_CONTEXTS = {
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_REGISTER: 'AUTH_REGISTER',

    ODIN_CREATE_ITEM: 'ODIN_CREATE_ITEM',
    ODIN_UPDATE_ITEM: 'ODIN_UPDATE_ITEM',
    ODIN_DELETE_ITEM: 'ODIN_DELETE_ITEM',

    ODIN_CREATE_SUBCATEGORY: 'ODIN_CREATE_SUBCATEGORY',
    ODIN_UPDATE_SUBCATEGORY: 'ODIN_UPDATE_SUBCATEGORY',

    ODIN_CREATE_BOX: 'ODIN_CREATE_BOX',
    ODIN_UPDATE_BOX: 'ODIN_UPDATE_BOX',

    GENERAL: 'GENERAL'
} as const;
