/**
 * ODIN Onboarding — Type definitions
 * Enum for step identifiers.
 */

export enum OdinOnboardingStep {
    INTRO = 'INTRO',
    EXPLAIN_INCOME_SOURCE = 'EXPLAIN_INCOME_SOURCE',
    EXPLAIN_POOL = 'EXPLAIN_POOL',
    EXPLAIN_ALLOCATIONS = 'EXPLAIN_ALLOCATIONS',
    CREATE_FIRST_INCOME_SOURCE = 'CREATE_FIRST_INCOME_SOURCE',
    CREATE_FIRST_ALLOCATION_BOX = 'CREATE_FIRST_ALLOCATION_BOX',
    COMPLETED = 'COMPLETED'
}
